INSERT INTO USER (ID, MOVE_PLAN_ID, FEEDBACK_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, PASSWORD, CREATED_AT, UPDATED_AT)
VALUES (1, NULL, NULL, 'Ricky', 'Bobby', 'myemail@outlook.com', NULL, 'qiyh4XPJGsOZ2MEAyLkfWqeQ', NOW(), NOW()),
       (2, NULL, NULL, 'John' , 'Smith', 'john.smith@test.net', '555-555-5555', 'BlueMango@1', NOW(), NOW());

INSERT INTO BOX_SIZE (ID, DESCRIPTION, DIMENSIONS, CREATED_AT, UPDATED_AT )
VALUES
(1,'Standard Box', '10x15x25', NOW(), NOW()),
(2,'Fine China Box', '15x12x28', NOW(), NOW()),
(3,'Stash Box', '18x29x45', NOW(), NOW()),
(4,'Poster Box', '67x10x12', NOW(), NOW()),
(5,'TV Box', '90x12x40', NOW(), NOW());

INSERT INTO ROLE (DESCRIPTION)
VALUES ('Standard User'), ('Administrator User');

INSERT INTO MOVE_PLAN (`ID`, `CREATED_AT`, `UPDATED_AT`)
VALUES(1, NOW(), NOW());

INSERT INTO USER_INVENTORY_ITEM (MOVE_PLAN_ID, ITEM_DESCRIPTION, FRAGILITY, WEIGHT, CREATED_AT, UPDATED_AT)
VALUES (1, 'FAMILY PICTURES', '2', 234.5, NOW(), NOW());

/* NOW RICKY BOBBY HAS A MOVE PLAN. WE CAN LINK THE MOVE PLAN IN THE USER TABLE THIS WAY. */
UPDATE
    USER
SET
    MOVE_PLAN_ID = 1
WHERE
    ID = 1;

/* sample query on how the tables are linked*/

/*
SELECT
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    UII.ITEM_DESCRIPTION,
    WEIGHT
FROM
    USER

        INNER JOIN
    MOVE_PLAN ON USER.MOVE_PLAN_ID = MOVE_PLAN.ID
        INNER JOIN
    USER_INVENTORY_ITEM UII on MOVE_PLAN.ID = UII.MOVE_PLAN_ID

 */

